#!/bin/bash
export DOCKER_REGISTRY=""
export VERSION="1.0.0"
export OUTPUT="deploy"

create-deployment()
{
  # Create k8s deployment file with substituted env variable
  # Note: ^ capitalizes the first letter.
  local env=$2
  export ASPNETCORE_ENVIRONMENT="${env^}"
  envsubst < ${1} > "${OUTPUT}/deployment.${env}.yaml"

  return 0
}

docker build -t "hello-world-job:v${VERSION}" --build-arg VERSION="${VERSION}" -f "src/HelloWorldJob/Dockerfile" .

mkdir -p $OUTPUT
create-deployment "kube/deployment.yaml" "development"
create-deployment "kube/deployment.yaml" "production"
